/**
 * MODULE SCAN — auto-generated from every real route in this app
 * (TanStack routes in src/routeTree.gen.ts + legacy routes in src/App.tsx).
 * Only routes NOT already present in MODULE_CATALOG are listed here, so the
 * sidebar can show every module without duplicates.
 */
import { Boxes } from "lucide-react";
import type { ModuleEntry } from "@/lib/module-catalog";

export const SCANNED_MODULES: ModuleEntry[] = [
  { id: "scan-access-denied", label: "Access Denied", path: "/access-denied", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-account-suspension", label: "Account Suspension", path: "/account-suspension", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-admin", label: "Admin", path: "/admin", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-admin-role-manager", label: "Admin Role Manager", path: "/admin/role-manager", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-ams-new", label: "Ams New", path: "/ams/new", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-apply", label: "Apply", path: "/apply", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-auth", label: "Auth", path: "/auth", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards", label: "Awards", path: "/awards", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-audit", label: "Awards Audit", path: "/awards/audit", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-categories", label: "Awards Categories", path: "/awards/categories", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-effects", label: "Awards Effects", path: "/awards/effects", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-libraries-achievements", label: "Awards Libraries Achievements", path: "/awards/libraries/achievements", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-libraries-badges", label: "Awards Libraries Badges", path: "/awards/libraries/badges", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-libraries-ranks", label: "Awards Libraries Ranks", path: "/awards/libraries/ranks", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-libraries-trophies", label: "Awards Libraries Trophies", path: "/awards/libraries/trophies", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-rules-levels", label: "Awards Rules Levels", path: "/awards/rules/levels", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-rules-milestones", label: "Awards Rules Milestones", path: "/awards/rules/milestones", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-rules-rewards", label: "Awards Rules Rewards", path: "/awards/rules/rewards", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-rules-streaks", label: "Awards Rules Streaks", path: "/awards/rules/streaks", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-awards-rules-xp", label: "Awards Rules Xp", path: "/awards/rules/xp", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-bootstrap-admins", label: "Bootstrap Admins", path: "/bootstrap-admins", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-boss-register", label: "Boss Register", path: "/boss-register", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-boss-login", label: "Boss Login", path: "/boss/login", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-bulk-actions", label: "Bulk Actions", path: "/bulk-actions", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-buzzer-console", label: "Buzzer Console", path: "/buzzer-console", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-careers", label: "Careers", path: "/careers", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-change-password", label: "Change Password", path: "/change-password", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-continent-super-admin", label: "Continent Super Admin", path: "/continent-super-admin", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo", label: "Demo", path: "/demo", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-credentials", label: "Demo Credentials", path: "/demo-credentials", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-login", label: "Demo Login", path: "/demo-login", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-order-system", label: "Demo Order System", path: "/demo-order-system", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-automotive", label: "Demo Automotive", path: "/demo/automotive", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-childcare", label: "Demo Childcare", path: "/demo/childcare", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-crm", label: "Demo Crm", path: "/demo/crm", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-ecommerce-store", label: "Demo Ecommerce Store", path: "/demo/ecommerce-store", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-education", label: "Demo Education", path: "/demo/education", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-event", label: "Demo Event", path: "/demo/event", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-finance", label: "Demo Finance", path: "/demo/finance", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-gym", label: "Demo Gym", path: "/demo/gym", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-hospital-hms", label: "Demo Hospital Hms", path: "/demo/hospital-hms", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-hotel-booking", label: "Demo Hotel Booking", path: "/demo/hotel-booking", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-influencer-command-center", label: "Demo Influencer Command Center", path: "/demo/influencer-command-center", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-legal", label: "Demo Legal", path: "/demo/legal", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-logistics", label: "Demo Logistics", path: "/demo/logistics", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-manufacturing", label: "Demo Manufacturing", path: "/demo/manufacturing", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-petcare", label: "Demo Petcare", path: "/demo/petcare", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-real-estate", label: "Demo Real Estate", path: "/demo/real-estate", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-restaurant-large", label: "Demo Restaurant Large", path: "/demo/restaurant-large", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-restaurant-medium", label: "Demo Restaurant Medium", path: "/demo/restaurant-medium", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-restaurant-pos", label: "Demo Restaurant Pos", path: "/demo/restaurant-pos", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-restaurant-small", label: "Demo Restaurant Small", path: "/demo/restaurant-small", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-salon", label: "Demo Salon", path: "/demo/salon", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-school-erp", label: "Demo School Erp", path: "/demo/school-erp", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-school-large", label: "Demo School Large", path: "/demo/school-large", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-school-medium", label: "Demo School Medium", path: "/demo/school-medium", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-school-small", label: "Demo School Small", path: "/demo/school-small", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-security", label: "Demo Security", path: "/demo/security", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-telecom", label: "Demo Telecom", path: "/demo/telecom", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demo-travel", label: "Demo Travel", path: "/demo/travel", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demos", label: "Demos", path: "/demos", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demos-education", label: "Demos Education", path: "/demos/education", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-demos-public", label: "Demos Public", path: "/demos/public", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-developer", label: "Developer", path: "/developer", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-developer-dashboard", label: "Developer Dashboard", path: "/developer/dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-developer-register", label: "Developer Register", path: "/developer/register", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-developer-registration", label: "Developer Registration", path: "/developer/registration", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-device-verify", label: "Device Verify", path: "/device-verify", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-easy-login", label: "Easy Login", path: "/easy-login", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-explore", label: "Explore", path: "/explore", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-forgot-password", label: "Forgot Password", path: "/forgot-password", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise", label: "Franchise", path: "/franchise", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-dashboard", label: "Franchise Dashboard", path: "/franchise-dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-landing", label: "Franchise Landing", path: "/franchise-landing", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-program", label: "Franchise Program", path: "/franchise-program", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-assign-lead", label: "Franchise Assign Lead", path: "/franchise/assign-lead", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-demo-library", label: "Franchise Demo Library", path: "/franchise/demo-library", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-demo-request", label: "Franchise Demo Request", path: "/franchise/demo-request", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-hrm", label: "Franchise Hrm", path: "/franchise/hrm", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-internal-chat", label: "Franchise Internal Chat", path: "/franchise/internal-chat", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-lead-activity", label: "Franchise Lead Activity", path: "/franchise/lead-activity", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-lead-board", label: "Franchise Lead Board", path: "/franchise/lead-board", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-performance", label: "Franchise Performance", path: "/franchise/performance", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-profile", label: "Franchise Profile", path: "/franchise/profile", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-security-panel", label: "Franchise Security Panel", path: "/franchise/security-panel", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-seo-services", label: "Franchise Seo Services", path: "/franchise/seo-services", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-support-ticket", label: "Franchise Support Ticket", path: "/franchise/support-ticket", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-team-management", label: "Franchise Team Management", path: "/franchise/team-management", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-franchise-training-center", label: "Franchise Training Center", path: "/franchise/training-center", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-get-started", label: "Get Started", path: "/get-started", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-hr", label: "Hr", path: "/hr", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-influencer", label: "Influencer", path: "/influencer", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-influencer-command-center", label: "Influencer Command Center", path: "/influencer-command-center", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-influencer-manager-secure", label: "Influencer Manager Secure", path: "/influencer-manager-secure", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-influencer-command-center", label: "Influencer Command Center", path: "/influencer/command-center", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-influencer-dashboard", label: "Influencer Dashboard", path: "/influencer/dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-ip-verify", label: "Ip Verify", path: "/ip-verify", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-jobs", label: "Jobs", path: "/jobs", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-join-developer", label: "Join Developer", path: "/join-developer", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-join-influencer", label: "Join Influencer", path: "/join-influencer", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-leader-security", label: "Leader Security", path: "/leader-security", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-legal", label: "Legal", path: "/legal", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-legal-manager-secure", label: "Legal Manager Secure", path: "/legal-manager-secure", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-login", label: "Login", path: "/login", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-logout", label: "Logout", path: "/logout", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-marketing", label: "Marketing", path: "/marketing", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-missions", label: "Missions", path: "/missions", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-module-switch", label: "Module Switch", path: "/module-switch", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-onboard", label: "Onboard", path: "/onboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-otp-verify", label: "Otp Verify", path: "/otp-verify", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-pending-approval", label: "Pending Approval", path: "/pending-approval", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-personal-chat", label: "Personal Chat", path: "/personal-chat", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-prime", label: "Prime", path: "/prime", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-prime-user", label: "Prime User", path: "/prime-user", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-product-demo-manager", label: "Product Demo Manager", path: "/product-demo-manager", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-quests", label: "Quests", path: "/quests", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-quick-signup", label: "Quick Signup", path: "/quick-signup", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-register", label: "Register", path: "/register", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller", label: "Reseller", path: "/reseller", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller-landing", label: "Reseller Landing", path: "/reseller-landing", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller-manager-secure", label: "Reseller Manager Secure", path: "/reseller-manager-secure", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller-portal", label: "Reseller Portal", path: "/reseller-portal", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller-program", label: "Reseller Program", path: "/reseller-program", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller-dashboard", label: "Reseller Dashboard", path: "/reseller/dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reseller-portal", label: "Reseller Portal", path: "/reseller/portal", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-reset-password", label: "Reset Password", path: "/reset-password", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-role-login", label: "Role Login", path: "/role-login", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-sales-crm-auth", label: "Sales Crm Auth", path: "/sales-crm/auth", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-sales-support", label: "Sales Support", path: "/sales-support", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-sales-support-manager-secure", label: "Sales Support Manager Secure", path: "/sales-support-manager-secure", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-school-software", label: "School Software", path: "/school-software", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-seo", label: "Seo", path: "/seo", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-session-expired", label: "Session Expired", path: "/session-expired", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-softwarewala", label: "Softwarewala", path: "/softwarewala", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system", label: "Super Admin System", path: "/super-admin-system", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-audit", label: "Super Admin System Audit", path: "/super-admin-system/audit", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-geography", label: "Super Admin System Geography", path: "/super-admin-system/geography", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-locks", label: "Super Admin System Locks", path: "/super-admin-system/locks", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-login", label: "Super Admin System Login", path: "/super-admin-system/login", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-rc", label: "Super Admin System Rc", path: "/super-admin-system/rc", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-rentals", label: "Super Admin System Rentals", path: "/super-admin-system/rentals", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-roles", label: "Super Admin System Roles", path: "/super-admin-system/roles", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-rules", label: "Super Admin System Rules", path: "/super-admin-system/rules", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-security", label: "Super Admin System Security", path: "/super-admin-system/security", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-users", label: "Super Admin System Users", path: "/super-admin-system/users", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-dashboard", label: "Super Admin Dashboard", path: "/super-admin/dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-demo-manager", label: "Super Admin Demo Manager", path: "/super-admin/demo-manager", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-influencer-manager", label: "Super Admin Influencer Manager", path: "/super-admin/influencer-manager", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-live-tracking", label: "Super Admin Live Tracking", path: "/super-admin/live-tracking", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-performance", label: "Super Admin Performance", path: "/super-admin/performance", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-prime-manager", label: "Super Admin Prime Manager", path: "/super-admin/prime-manager", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-support-center", label: "Super Admin Support Center", path: "/super-admin/support-center", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-super-admin-system-settings", label: "Super Admin System Settings", path: "/super-admin/system-settings", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-support", label: "Support", path: "/support", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-task-manager-secure", label: "Task Manager Secure", path: "/task-manager-secure", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-trophy-gallery", label: "Trophy Gallery", path: "/trophy-gallery", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-user-dashboard", label: "User Dashboard", path: "/user-dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-user-dashboard", label: "User Dashboard", path: "/user/dashboard", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-vala", label: "Vala", path: "/vala", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-vala-control-ai-head", label: "Vala Control Ai Head", path: "/vala-control/ai-head", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-vala-ai-head", label: "Vala Ai Head", path: "/vala/ai-head", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-vala-master", label: "Vala Master", path: "/vala/master", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-vala-operation", label: "Vala Operation", path: "/vala/operation", icon: Boxes, group: "All Modules (Scanned)" },
  { id: "scan-vala-regional", label: "Vala Regional", path: "/vala/regional", icon: Boxes, group: "All Modules (Scanned)" },
];
