import {
  Activity,
  Bug,
  Code2,
  FileText,
  Handshake,
  Megaphone,
  Search,
  Server,
  Shield,
  Sparkles,
  ListChecks,
  BadgeCheck,
  Banknote,
  Boxes,
  Building2,
  CircleDollarSign,
  Clock,
  LifeBuoy,
  ShoppingCart,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface KpiTemplate {
  key: string;
  label: string;
  icon: LucideIcon;
  tone?: "brand" | "success" | "warning" | "danger" | "neutral";
  unit?: string;
}

export interface ModuleDefinition {
  /** API endpoint key: GET {API_BASE}/dashboards/{moduleKey} */
  moduleKey: string;
  kicker: string;
  title: string;
  description: string;
  kpis: KpiTemplate[];
  table: { title: string; columns: { key: string; header: string }[] };
}

/**
 * Every module inherits the SAME dashboard template — only this config
 * (KPIs, table columns, data endpoint) differs.
 */
export const MODULES: Record<string, ModuleDefinition> = {
  boss: {
    moduleKey: "boss",
    kicker: "Command",
    title: "Boss Panel",
    description: "Company-wide performance across every module, from live records.",
    kpis: [
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "orders", label: "Orders", icon: ShoppingCart },
      { key: "users", label: "Active Users", icon: Users },
      { key: "modules", label: "Live Modules", icon: Boxes, tone: "neutral" },
      { key: "alerts", label: "Open Alerts", icon: Activity, tone: "warning" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Recent Company Activity",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "super-admin": {
    moduleKey: "super-admin",
    kicker: "Administration",
    title: "Super Admin",
    description: "Platform administration, roles and system health from live records.",
    kpis: [
      { key: "users", label: "Users", icon: Users },
      { key: "roles", label: "Roles", icon: UserCheck },
      { key: "sessions", label: "Active Sessions", icon: Activity },
      { key: "incidents", label: "Incidents", icon: Clock, tone: "warning" },
      { key: "modules", label: "Modules", icon: Boxes, tone: "neutral" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "System Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "entity", header: "Entity" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  ceo: {
    moduleKey: "ceo",
    kicker: "Executive",
    title: "CEO Dashboard",
    description: "Executive KPIs sourced directly from the company database.",
    kpis: [
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "growth", label: "Growth", icon: TrendingUp, unit: "%" },
      { key: "customers", label: "Customers", icon: Users },
      { key: "pipeline", label: "Pipeline", icon: Target },
      { key: "burn", label: "Burn", icon: Banknote, tone: "warning" },
      { key: "runway", label: "Runway", icon: Clock, tone: "neutral" },
    ],
    table: {
      title: "Executive Records",
      columns: [
        { key: "period", header: "Period" },
        { key: "metric", header: "Metric" },
        { key: "value", header: "Value" },
        { key: "change", header: "Change" },
      ],
    },
  },
  finance: {
    moduleKey: "finance",
    kicker: "Finance",
    title: "Finance Manager",
    description: "Invoices, payouts and balances from the finance database.",
    kpis: [
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "expenses", label: "Expenses", icon: Banknote, tone: "warning" },
      { key: "profit", label: "Profit", icon: TrendingUp, tone: "success" },
      { key: "receivables", label: "Receivables", icon: Wallet },
      { key: "payables", label: "Payables", icon: Wallet, tone: "danger" },
      { key: "invoices", label: "Invoices", icon: Boxes, tone: "neutral" },
    ],
    table: {
      title: "Transactions",
      columns: [
        { key: "created_at", header: "Date" },
        { key: "reference", header: "Reference" },
        { key: "party", header: "Party" },
        { key: "amount", header: "Amount" },
        { key: "status", header: "Status" },
      ],
    },
  },
  crm: {
    moduleKey: "crm",
    kicker: "Revenue",
    title: "CRM & Leads",
    description: "Leads, deals and conversion performance from live CRM records.",
    kpis: [
      { key: "leads", label: "Leads", icon: Target },
      { key: "qualified", label: "Qualified", icon: UserCheck, tone: "success" },
      { key: "deals", label: "Open Deals", icon: Boxes },
      { key: "won", label: "Won", icon: BadgeCheck, tone: "success" },
      { key: "conversion", label: "Conversion", icon: TrendingUp, unit: "%" },
      { key: "value", label: "Pipeline Value", icon: CircleDollarSign },
    ],
    table: {
      title: "Leads",
      columns: [
        { key: "created_at", header: "Created" },
        { key: "name", header: "Lead" },
        { key: "owner", header: "Owner" },
        { key: "stage", header: "Stage" },
        { key: "value", header: "Value" },
      ],
    },
  },
  support: {
    moduleKey: "support",
    kicker: "Service",
    title: "Support Manager",
    description: "Tickets, SLA and satisfaction from the support database.",
    kpis: [
      { key: "open", label: "Open Tickets", icon: LifeBuoy, tone: "warning" },
      { key: "resolved", label: "Resolved", icon: BadgeCheck, tone: "success" },
      { key: "first_response", label: "First Response", icon: Clock },
      { key: "sla", label: "SLA Met", icon: Target, unit: "%" },
      { key: "csat", label: "CSAT", icon: TrendingUp, unit: "%" },
      { key: "agents", label: "Agents Online", icon: Users, tone: "neutral" },
    ],
    table: {
      title: "Tickets",
      columns: [
        { key: "created_at", header: "Created" },
        { key: "reference", header: "Ticket" },
        { key: "customer", header: "Customer" },
        { key: "priority", header: "Priority" },
        { key: "status", header: "Status" },
      ],
    },
  },
  vendor: {
    moduleKey: "vendor",
    kicker: "Marketplace",
    title: "Vendor Manager",
    description: "Vendors, catalogue and settlements from live marketplace data.",
    kpis: [
      { key: "vendors", label: "Vendors", icon: Building2 },
      { key: "active", label: "Active", icon: BadgeCheck, tone: "success" },
      { key: "products", label: "Products", icon: Boxes },
      { key: "orders", label: "Orders", icon: ShoppingCart },
      { key: "gmv", label: "GMV", icon: CircleDollarSign, tone: "success" },
      { key: "payouts", label: "Pending Payouts", icon: Wallet, tone: "warning" },
    ],
    table: {
      title: "Vendors",
      columns: [
        { key: "name", header: "Vendor" },
        { key: "category", header: "Category" },
        { key: "orders", header: "Orders" },
        { key: "gmv", header: "GMV" },
        { key: "status", header: "Status" },
      ],
    },
  },
  franchise: {
    moduleKey: "franchise",
    kicker: "Network",
    title: "Franchise Manager",
    description: "Franchise network performance from live franchise records.",
    kpis: [
      { key: "franchises", label: "Franchises", icon: Building2 },
      { key: "active", label: "Active", icon: BadgeCheck, tone: "success" },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "leads", label: "Leads", icon: Target },
      { key: "renewals", label: "Renewals Due", icon: Clock, tone: "warning" },
      { key: "territories", label: "Territories", icon: Boxes, tone: "neutral" },
    ],
    table: {
      title: "Franchises",
      columns: [
        { key: "name", header: "Franchise" },
        { key: "territory", header: "Territory" },
        { key: "revenue", header: "Revenue" },
        { key: "renewal_at", header: "Renewal" },
        { key: "status", header: "Status" },
      ],
    },
  },
  marketing: {
    moduleKey: "marketing",
    kicker: "Growth",
    title: "Marketing Manager",
    description: "Campaigns, channels and spend from live marketing records.",
    kpis: [
      { key: "campaigns", label: "Campaigns", icon: Megaphone },
      { key: "impressions", label: "Impressions", icon: Activity },
      { key: "clicks", label: "Clicks", icon: Target },
      { key: "leads", label: "Leads", icon: Users, tone: "success" },
      { key: "spend", label: "Spend", icon: CircleDollarSign, tone: "warning" },
      { key: "roas", label: "ROAS", icon: TrendingUp },
    ],
    table: {
      title: "Campaigns",
      columns: [
        { key: "created_at", header: "Started" },
        { key: "name", header: "Campaign" },
        { key: "channel", header: "Channel" },
        { key: "spend", header: "Spend" },
        { key: "status", header: "Status" },
      ],
    },
  },
  reseller: {
    moduleKey: "reseller",
    kicker: "Partners",
    title: "Reseller Manager",
    description: "Reseller network, sales and commissions from live records.",
    kpis: [
      { key: "resellers", label: "Resellers", icon: Handshake },
      { key: "active", label: "Active", icon: BadgeCheck, tone: "success" },
      { key: "sales", label: "Sales", icon: ShoppingCart },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "commission", label: "Commission Due", icon: Wallet, tone: "warning" },
      { key: "tiers", label: "Tiers", icon: Boxes, tone: "neutral" },
    ],
    table: {
      title: "Resellers",
      columns: [
        { key: "name", header: "Reseller" },
        { key: "tier", header: "Tier" },
        { key: "sales", header: "Sales" },
        { key: "commission", header: "Commission" },
        { key: "status", header: "Status" },
      ],
    },
  },
  hr: {
    moduleKey: "hr",
    kicker: "People",
    title: "HR Manager",
    description: "Headcount, attendance and hiring from live HR records.",
    kpis: [
      { key: "employees", label: "Employees", icon: Users },
      { key: "present", label: "Present Today", icon: UserCheck, tone: "success" },
      { key: "on_leave", label: "On Leave", icon: Clock, tone: "warning" },
      { key: "open_roles", label: "Open Roles", icon: Target },
      { key: "candidates", label: "Candidates", icon: Boxes },
      { key: "payroll", label: "Payroll", icon: Banknote },
    ],
    table: {
      title: "Employees",
      columns: [
        { key: "name", header: "Employee" },
        { key: "department", header: "Department" },
        { key: "role", header: "Role" },
        { key: "joined_at", header: "Joined" },
        { key: "status", header: "Status" },
      ],
    },
  },
  seo: {
    moduleKey: "seo",
    kicker: "Organic",
    title: "SEO Manager",
    description: "Rankings, traffic and technical health from live SEO data.",
    kpis: [
      { key: "keywords", label: "Keywords", icon: Search },
      { key: "top10", label: "Top 10", icon: BadgeCheck, tone: "success" },
      { key: "traffic", label: "Organic Traffic", icon: TrendingUp },
      { key: "backlinks", label: "Backlinks", icon: Activity },
      { key: "issues", label: "Issues", icon: Bug, tone: "warning" },
      { key: "score", label: "Health Score", icon: Target, unit: "%" },
    ],
    table: {
      title: "Tracked Pages",
      columns: [
        { key: "url", header: "Page" },
        { key: "keyword", header: "Keyword" },
        { key: "position", header: "Position" },
        { key: "traffic", header: "Traffic" },
        { key: "status", header: "Status" },
      ],
    },
  },
  legal: {
    moduleKey: "legal",
    kicker: "Compliance",
    title: "Legal & Compliance",
    description: "Contracts, disputes and compliance from live legal records.",
    kpis: [
      { key: "contracts", label: "Contracts", icon: FileText },
      { key: "pending", label: "Pending Review", icon: Clock, tone: "warning" },
      { key: "expiring", label: "Expiring", icon: Activity, tone: "danger" },
      { key: "disputes", label: "Disputes", icon: Shield, tone: "danger" },
      { key: "policies", label: "Policies", icon: Boxes, tone: "neutral" },
      { key: "compliance", label: "Compliance", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Contracts",
      columns: [
        { key: "reference", header: "Reference" },
        { key: "party", header: "Party" },
        { key: "type", header: "Type" },
        { key: "expires_at", header: "Expires" },
        { key: "status", header: "Status" },
      ],
    },
  },
  task: {
    moduleKey: "task",
    kicker: "Delivery",
    title: "Task Manager",
    description: "Tasks, owners and delivery status from live project records.",
    kpis: [
      { key: "tasks", label: "Tasks", icon: ListChecks },
      { key: "in_progress", label: "In Progress", icon: Activity },
      { key: "completed", label: "Completed", icon: BadgeCheck, tone: "success" },
      { key: "overdue", label: "Overdue", icon: Clock, tone: "danger" },
      { key: "assignees", label: "Assignees", icon: Users, tone: "neutral" },
      { key: "on_time", label: "On Time", icon: Target, unit: "%" },
    ],
    table: {
      title: "Tasks",
      columns: [
        { key: "title", header: "Task" },
        { key: "assignee", header: "Assignee" },
        { key: "due_at", header: "Due" },
        { key: "priority", header: "Priority" },
        { key: "status", header: "Status" },
      ],
    },
  },
  influencer: {
    moduleKey: "influencer",
    kicker: "Creators",
    title: "Influencer Manager",
    description: "Creators, collaborations and payouts from live records.",
    kpis: [
      { key: "influencers", label: "Influencers", icon: Sparkles },
      { key: "active", label: "Active", icon: BadgeCheck, tone: "success" },
      { key: "campaigns", label: "Campaigns", icon: Megaphone },
      { key: "reach", label: "Reach", icon: Activity },
      { key: "conversions", label: "Conversions", icon: Target, tone: "success" },
      { key: "payouts", label: "Pending Payouts", icon: Wallet, tone: "warning" },
    ],
    table: {
      title: "Influencers",
      columns: [
        { key: "name", header: "Influencer" },
        { key: "platform", header: "Platform" },
        { key: "reach", header: "Reach" },
        { key: "conversions", header: "Conversions" },
        { key: "status", header: "Status" },
      ],
    },
  },
  developer: {
    moduleKey: "developer",
    kicker: "Engineering",
    title: "Developer Dashboard",
    description: "Builds, issues and deployment health from live engineering data.",
    kpis: [
      { key: "projects", label: "Projects", icon: Code2 },
      { key: "deployments", label: "Deployments", icon: Activity },
      { key: "open_bugs", label: "Open Bugs", icon: Bug, tone: "danger" },
      { key: "prs", label: "Open PRs", icon: Boxes },
      { key: "coverage", label: "Coverage", icon: Target, unit: "%" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Recent Builds",
      columns: [
        { key: "created_at", header: "When" },
        { key: "project", header: "Project" },
        { key: "branch", header: "Branch" },
        { key: "author", header: "Author" },
        { key: "status", header: "Status" },
      ],
    },
  },
  security: {
    moduleKey: "security",
    kicker: "Security",
    title: "Security Command",
    description: "Threats, access and audit signals from live security records.",
    kpis: [
      { key: "alerts", label: "Open Alerts", icon: Shield, tone: "danger" },
      { key: "blocked", label: "Blocked", icon: BadgeCheck, tone: "success" },
      { key: "sessions", label: "Active Sessions", icon: Activity },
      { key: "failed_logins", label: "Failed Logins", icon: Clock, tone: "warning" },
      { key: "policies", label: "Policies", icon: Boxes, tone: "neutral" },
      { key: "score", label: "Security Score", icon: Target, unit: "%" },
    ],
    table: {
      title: "Security Events",
      columns: [
        { key: "created_at", header: "When" },
        { key: "event", header: "Event" },
        { key: "actor", header: "Actor" },
        { key: "severity", header: "Severity" },
        { key: "status", header: "Status" },
      ],
    },
  },
  server: {
    moduleKey: "server",
    kicker: "Infrastructure",
    title: "Server Manager",
    description: "Servers, load and incidents from live infrastructure data.",
    kpis: [
      { key: "servers", label: "Servers", icon: Server },
      { key: "healthy", label: "Healthy", icon: BadgeCheck, tone: "success" },
      { key: "cpu", label: "Avg CPU", icon: Activity, unit: "%" },
      { key: "memory", label: "Avg Memory", icon: Boxes, unit: "%" },
      { key: "incidents", label: "Incidents", icon: Clock, tone: "warning" },
      { key: "uptime", label: "Uptime", icon: Target, unit: "%", tone: "success" },
    ],
    table: {
      title: "Servers",
      columns: [
        { key: "name", header: "Server" },
        { key: "region", header: "Region" },
        { key: "cpu", header: "CPU" },
        { key: "memory", header: "Memory" },
        { key: "status", header: "Status" },
      ],
    },
  },

  /* ---------------- Batch 3 ---------------- */

  "master-admin": {
    moduleKey: "master-admin",
    kicker: "Administration",
    title: "Master Admin",
    description: "Master control over tenants, roles and platform records.",
    kpis: [
      { key: "tenants", label: "Tenants", icon: Building2 },
      { key: "users", label: "Users", icon: Users },
      { key: "roles", label: "Roles", icon: UserCheck },
      { key: "approvals", label: "Pending Approvals", icon: Clock, tone: "warning" },
      { key: "modules", label: "Modules", icon: Boxes, tone: "neutral" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Administration Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "entity", header: "Entity" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "role-manager": {
    moduleKey: "role-manager",
    kicker: "Access Control",
    title: "Role Manager",
    description: "Roles, permissions and approval requests from live records.",
    kpis: [
      { key: "roles", label: "Roles", icon: UserCheck },
      { key: "permissions", label: "Permissions", icon: Shield },
      { key: "assigned_users", label: "Assigned Users", icon: Users },
      { key: "pending", label: "Pending Requests", icon: Clock, tone: "warning" },
      { key: "elevated", label: "Elevated Access", icon: BadgeCheck, tone: "danger" },
      { key: "changes", label: "Changes (30d)", icon: Activity, tone: "neutral" },
    ],
    table: {
      title: "Roles & Requests",
      columns: [
        { key: "role", header: "Role" },
        { key: "scope", header: "Scope" },
        { key: "users", header: "Users" },
        { key: "requested_by", header: "Requested By" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "product-manager": {
    moduleKey: "product-manager",
    kicker: "Product",
    title: "Product Manager",
    description: "Products, releases and adoption from the product database.",
    kpis: [
      { key: "products", label: "Products", icon: Boxes },
      { key: "releases", label: "Releases", icon: Sparkles },
      { key: "active_users", label: "Active Users", icon: Users },
      { key: "bugs", label: "Open Bugs", icon: Bug, tone: "warning" },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "roadmap", label: "Roadmap Items", icon: ListChecks, tone: "neutral" },
    ],
    table: {
      title: "Products",
      columns: [
        { key: "name", header: "Product" },
        { key: "version", header: "Version" },
        { key: "owner", header: "Owner" },
        { key: "users", header: "Users" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "boss-owner": {
    moduleKey: "boss-owner",
    kicker: "Ownership",
    title: "Boss / Owner Dashboard",
    description: "Owner-level view of company performance from live records.",
    kpis: [
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "profit", label: "Profit", icon: TrendingUp, tone: "success" },
      { key: "companies", label: "Companies", icon: Building2 },
      { key: "employees", label: "Employees", icon: Users },
      { key: "alerts", label: "Open Alerts", icon: Activity, tone: "warning" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Owner Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "company", header: "Company" },
        { key: "metric", header: "Metric" },
        { key: "value", header: "Value" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "vala-ai": {
    moduleKey: "vala-ai",
    kicker: "Intelligence",
    title: "Vala AI Command Center",
    description: "AI workloads, usage and quality metrics from live records.",
    kpis: [
      { key: "requests", label: "Requests", icon: Activity },
      { key: "tokens", label: "Tokens", icon: Sparkles },
      { key: "agents", label: "Agents", icon: Boxes },
      { key: "cost", label: "Cost", icon: Wallet, tone: "warning" },
      { key: "success_rate", label: "Success Rate", icon: BadgeCheck, unit: "%", tone: "success" },
      { key: "latency", label: "Avg Latency", icon: Clock, tone: "neutral" },
    ],
    table: {
      title: "AI Activity",
      columns: [
        { key: "created_at", header: "When" },
        { key: "agent", header: "Agent" },
        { key: "task", header: "Task" },
        { key: "tokens", header: "Tokens" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "continent-admin": {
    moduleKey: "continent-admin",
    kicker: "Regions",
    title: "Continent Super Admin",
    description: "Continent-level operations and regional performance from live data.",
    kpis: [
      { key: "countries", label: "Countries", icon: Building2 },
      { key: "franchises", label: "Franchises", icon: Handshake },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "users", label: "Users", icon: Users },
      { key: "escalations", label: "Escalations", icon: Clock, tone: "warning" },
      { key: "growth", label: "Growth", icon: TrendingUp, unit: "%" },
    ],
    table: {
      title: "Regional Records",
      columns: [
        { key: "region", header: "Region" },
        { key: "country", header: "Country" },
        { key: "lead", header: "Lead" },
        { key: "revenue", header: "Revenue" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "country-head": {
    moduleKey: "country-head",
    kicker: "Regions",
    title: "Country Head Dashboard",
    description: "Country operations, teams and targets from live records.",
    kpis: [
      { key: "states", label: "States", icon: Building2 },
      { key: "teams", label: "Teams", icon: Users },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "target", label: "Target", icon: Target },
      { key: "escalations", label: "Escalations", icon: Clock, tone: "warning" },
      { key: "growth", label: "Growth", icon: TrendingUp, unit: "%" },
    ],
    table: {
      title: "Country Records",
      columns: [
        { key: "state", header: "State" },
        { key: "lead", header: "Lead" },
        { key: "revenue", header: "Revenue" },
        { key: "target", header: "Target" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "pro-manager": {
    moduleKey: "pro-manager",
    kicker: "Operations",
    title: "Pro Manager",
    description: "Professional services delivery and utilisation from live records.",
    kpis: [
      { key: "projects", label: "Projects", icon: Boxes },
      { key: "clients", label: "Clients", icon: Users },
      { key: "utilisation", label: "Utilisation", icon: Activity, unit: "%" },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "overdue", label: "Overdue", icon: Clock, tone: "warning" },
      { key: "csat", label: "CSAT", icon: BadgeCheck, tone: "success" },
    ],
    table: {
      title: "Engagements",
      columns: [
        { key: "project", header: "Project" },
        { key: "client", header: "Client" },
        { key: "owner", header: "Owner" },
        { key: "due_date", header: "Due" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "demo-manager": {
    moduleKey: "demo-manager",
    kicker: "Sales Enablement",
    title: "Demo Manager",
    description: "Demo accounts, sessions and conversions from live records.",
    kpis: [
      { key: "demos", label: "Demos", icon: Boxes },
      { key: "sessions", label: "Sessions", icon: Activity },
      { key: "leads", label: "Leads", icon: Target },
      { key: "conversions", label: "Conversions", icon: TrendingUp, tone: "success" },
      { key: "expiring", label: "Expiring", icon: Clock, tone: "warning" },
      { key: "accounts", label: "Demo Accounts", icon: Users, tone: "neutral" },
    ],
    table: {
      title: "Demo Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "demo", header: "Demo" },
        { key: "prospect", header: "Prospect" },
        { key: "owner", header: "Owner" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "super-admin-hierarchy": {
    moduleKey: "super-admin-hierarchy",
    kicker: "Administration",
    title: "Super Admin Hierarchy",
    description: "Hierarchy of admins, scopes and delegated access from live records.",
    kpis: [
      { key: "levels", label: "Levels", icon: Boxes },
      { key: "admins", label: "Admins", icon: UserCheck },
      { key: "scopes", label: "Scopes", icon: Shield },
      { key: "delegations", label: "Delegations", icon: Handshake },
      { key: "pending", label: "Pending", icon: Clock, tone: "warning" },
      { key: "active", label: "Active Sessions", icon: Activity, tone: "success" },
    ],
    table: {
      title: "Hierarchy Records",
      columns: [
        { key: "level", header: "Level" },
        { key: "admin", header: "Admin" },
        { key: "scope", header: "Scope" },
        { key: "parent", header: "Reports To" },
        { key: "status", header: "Status" },
      ],
    },
  },
  admin: {
    moduleKey: "admin",
    kicker: "Administration",
    title: "Admin Dashboard",
    description: "Day-to-day administration records from the live database.",
    kpis: [
      { key: "users", label: "Users", icon: Users },
      { key: "tickets", label: "Tickets", icon: LifeBuoy },
      { key: "approvals", label: "Approvals", icon: Clock, tone: "warning" },
      { key: "records", label: "Records", icon: FileText },
      { key: "modules", label: "Modules", icon: Boxes, tone: "neutral" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Admin Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "entity", header: "Entity" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "sales-support": {
    moduleKey: "sales-support",
    kicker: "Revenue",
    title: "Sales & Support Manager",
    description: "Sales pipeline and support workload from live records.",
    kpis: [
      { key: "leads", label: "Leads", icon: Target },
      { key: "deals", label: "Deals", icon: Handshake },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "tickets", label: "Open Tickets", icon: LifeBuoy, tone: "warning" },
      { key: "response_time", label: "Avg Response", icon: Clock },
      { key: "csat", label: "CSAT", icon: BadgeCheck, tone: "success" },
    ],
    table: {
      title: "Sales & Support Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "customer", header: "Customer" },
        { key: "type", header: "Type" },
        { key: "owner", header: "Owner" },
        { key: "status", header: "Status" },
      ],
    },
  },
  promise: {
    moduleKey: "promise",
    kicker: "Governance",
    title: "Promise Management",
    description: "Commitments, owners and delivery status from live records.",
    kpis: [
      { key: "promises", label: "Promises", icon: ListChecks },
      { key: "delivered", label: "Delivered", icon: BadgeCheck, tone: "success" },
      { key: "in_progress", label: "In Progress", icon: Activity },
      { key: "overdue", label: "Overdue", icon: Clock, tone: "danger" },
      { key: "owners", label: "Owners", icon: Users },
      { key: "on_time_rate", label: "On-time Rate", icon: TrendingUp, unit: "%", tone: "success" },
    ],
    table: {
      title: "Promises",
      columns: [
        { key: "promise", header: "Promise" },
        { key: "owner", header: "Owner" },
        { key: "due_date", header: "Due" },
        { key: "progress", header: "Progress" },
        { key: "status", header: "Status" },
      ],
    },
  },
  school: {
    moduleKey: "school",
    kicker: "Education",
    title: "School Software",
    description: "Schools, students and fee collection from live records.",
    kpis: [
      { key: "schools", label: "Schools", icon: Building2 },
      { key: "students", label: "Students", icon: Users },
      { key: "staff", label: "Staff", icon: UserCheck },
      { key: "attendance", label: "Attendance", icon: Activity, unit: "%" },
      { key: "fees_collected", label: "Fees Collected", icon: Wallet, tone: "success" },
      { key: "fees_due", label: "Fees Due", icon: Clock, tone: "warning" },
    ],
    table: {
      title: "School Records",
      columns: [
        { key: "school", header: "School" },
        { key: "students", header: "Students" },
        { key: "attendance", header: "Attendance" },
        { key: "fees_due", header: "Fees Due" },
        { key: "status", header: "Status" },
      ],
    },
  },
  api: {
    moduleKey: "api",
    kicker: "Integrations",
    title: "API Integrations",
    description: "Integrations, traffic and failures from live gateway records.",
    kpis: [
      { key: "integrations", label: "Integrations", icon: Code2 },
      { key: "requests", label: "Requests", icon: Activity },
      { key: "success_rate", label: "Success Rate", icon: BadgeCheck, unit: "%", tone: "success" },
      { key: "errors", label: "Errors", icon: Bug, tone: "danger" },
      { key: "latency", label: "Avg Latency", icon: Clock },
      { key: "keys", label: "Active Keys", icon: Shield, tone: "neutral" },
    ],
    table: {
      title: "Integrations",
      columns: [
        { key: "name", header: "Integration" },
        { key: "provider", header: "Provider" },
        { key: "requests", header: "Requests" },
        { key: "errors", header: "Errors" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "client-success": {
    moduleKey: "client-success",
    kicker: "Customers",
    title: "Client Success",
    description: "Account health, renewals and churn risk from live records.",
    kpis: [
      { key: "accounts", label: "Accounts", icon: Users },
      { key: "health_score", label: "Health Score", icon: BadgeCheck, tone: "success" },
      { key: "renewals", label: "Renewals Due", icon: Clock, tone: "warning" },
      { key: "churn_risk", label: "Churn Risk", icon: Activity, tone: "danger" },
      { key: "nps", label: "NPS", icon: TrendingUp },
      { key: "arr", label: "ARR", icon: CircleDollarSign, tone: "success" },
    ],
    table: {
      title: "Accounts",
      columns: [
        { key: "account", header: "Account" },
        { key: "owner", header: "Owner" },
        { key: "health_score", header: "Health" },
        { key: "renewal_date", header: "Renewal" },
        { key: "status", header: "Status" },
      ],
    },
  },
  incident: {
    moduleKey: "incident",
    kicker: "Reliability",
    title: "Incident & Crisis",
    description: "Live incidents, severity and resolution times from live records.",
    kpis: [
      { key: "open_incidents", label: "Open Incidents", icon: Activity, tone: "danger" },
      { key: "critical", label: "Critical", icon: Shield, tone: "danger" },
      { key: "resolved", label: "Resolved", icon: BadgeCheck, tone: "success" },
      { key: "mttr", label: "MTTR", icon: Clock },
      { key: "services_affected", label: "Services Hit", icon: Server, tone: "warning" },
      { key: "uptime", label: "Uptime", icon: TrendingUp, unit: "%", tone: "success" },
    ],
    table: {
      title: "Incidents",
      columns: [
        { key: "created_at", header: "Opened" },
        { key: "incident", header: "Incident" },
        { key: "severity", header: "Severity" },
        { key: "owner", header: "Owner" },
        { key: "status", header: "Status" },
      ],
    },
  },
  rnd: {
    moduleKey: "rnd",
    kicker: "Innovation",
    title: "R&D",
    description: "Research initiatives, experiments and delivery from live records.",
    kpis: [
      { key: "projects", label: "Projects", icon: Boxes },
      { key: "experiments", label: "Experiments", icon: Sparkles },
      { key: "shipped", label: "Shipped", icon: BadgeCheck, tone: "success" },
      { key: "blocked", label: "Blocked", icon: Clock, tone: "warning" },
      { key: "researchers", label: "Researchers", icon: Users },
      { key: "budget", label: "Budget", icon: Wallet },
    ],
    table: {
      title: "Initiatives",
      columns: [
        { key: "project", header: "Project" },
        { key: "owner", header: "Owner" },
        { key: "stage", header: "Stage" },
        { key: "progress", header: "Progress" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "prime-user": {
    moduleKey: "prime-user",
    kicker: "Membership",
    title: "Prime User",
    description: "Prime membership usage, benefits and billing from live records.",
    kpis: [
      { key: "plan_days_left", label: "Days Left", icon: Clock },
      { key: "usage", label: "Usage", icon: Activity, unit: "%" },
      { key: "modules", label: "Modules", icon: Boxes },
      { key: "invoices", label: "Invoices", icon: FileText },
      { key: "spend", label: "Spend", icon: CircleDollarSign },
      { key: "support_tickets", label: "Tickets", icon: LifeBuoy, tone: "warning" },
    ],
    table: {
      title: "Recent Activity",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  user: {
    moduleKey: "user",
    kicker: "Workspace",
    title: "My Dashboard",
    description: "Your modules, tasks and recent activity from live records.",
    kpis: [
      { key: "tasks", label: "Tasks", icon: ListChecks },
      { key: "due_today", label: "Due Today", icon: Clock, tone: "warning" },
      { key: "completed", label: "Completed", icon: BadgeCheck, tone: "success" },
      { key: "modules", label: "Modules", icon: Boxes },
      { key: "notifications", label: "Notifications", icon: Activity },
      { key: "messages", label: "Messages", icon: LifeBuoy },
    ],
    table: {
      title: "Recent Activity",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  billing: {
    moduleKey: "billing",
    kicker: "Finance",
    title: "Billing",
    description: "Invoices, collections and subscription revenue from live records.",
    kpis: [
      { key: "invoices", label: "Invoices", icon: FileText },
      { key: "paid", label: "Paid", icon: BadgeCheck, tone: "success" },
      { key: "outstanding", label: "Outstanding", icon: Clock, tone: "warning" },
      { key: "overdue", label: "Overdue", icon: Activity, tone: "danger" },
      { key: "mrr", label: "MRR", icon: CircleDollarSign, tone: "success" },
      { key: "refunds", label: "Refunds", icon: Banknote },
    ],
    table: {
      title: "Invoices",
      columns: [
        { key: "invoice_no", header: "Invoice" },
        { key: "customer", header: "Customer" },
        { key: "amount", header: "Amount" },
        { key: "due_date", header: "Due" },
        { key: "status", header: "Status" },
      ],
    },
  },
  business: {
    moduleKey: "business",
    kicker: "Operations",
    title: "Business",
    description: "Business performance, customers and orders from live records.",
    kpis: [
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "orders", label: "Orders", icon: ShoppingCart },
      { key: "customers", label: "Customers", icon: Users },
      { key: "products", label: "Products", icon: Boxes },
      { key: "growth", label: "Growth", icon: TrendingUp, unit: "%", tone: "success" },
      { key: "pending", label: "Pending", icon: Clock, tone: "warning" },
    ],
    table: {
      title: "Business Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "customer", header: "Customer" },
        { key: "amount", header: "Amount" },
        { key: "channel", header: "Channel" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "multi-branch": {
    moduleKey: "multi-branch",
    kicker: "Network",
    title: "Multi-Branch",
    description: "Branch performance, staff and sales from live records.",
    kpis: [
      { key: "branches", label: "Branches", icon: Building2 },
      { key: "employees", label: "Employees", icon: Users },
      { key: "sales", label: "Sales", icon: CircleDollarSign, tone: "success" },
      { key: "attendance", label: "Attendance", icon: UserCheck, unit: "%" },
      { key: "alerts", label: "Alerts", icon: Activity, tone: "warning" },
      { key: "top_branch", label: "Top Branch", icon: TrendingUp },
    ],
    table: {
      title: "Branches",
      columns: [
        { key: "branch", header: "Branch" },
        { key: "manager", header: "Manager" },
        { key: "employees", header: "Employees" },
        { key: "sales", header: "Sales" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "sales-crm": {
    moduleKey: "sales-crm",
    kicker: "Revenue",
    title: "Sales CRM",
    description: "Pipeline, deals and conversion from live records.",
    kpis: [
      { key: "leads", label: "Leads", icon: Target },
      { key: "deals", label: "Deals", icon: Handshake },
      { key: "won", label: "Won", icon: BadgeCheck, tone: "success" },
      { key: "pipeline_value", label: "Pipeline", icon: CircleDollarSign },
      { key: "conversion", label: "Conversion", icon: TrendingUp, unit: "%", tone: "success" },
      { key: "reps", label: "Reps", icon: Users },
    ],
    table: {
      title: "Pipeline",
      columns: [
        { key: "created_at", header: "When" },
        { key: "company", header: "Company" },
        { key: "value", header: "Value" },
        { key: "owner", header: "Owner" },
        { key: "stage", header: "Stage" },
      ],
    },
  },
  "safe-assist": {
    moduleKey: "safe-assist",
    kicker: "Assistance",
    title: "Safe Assist",
    description: "Assist requests, escalations and resolution from live records.",
    kpis: [
      { key: "requests", label: "Requests", icon: LifeBuoy },
      { key: "open", label: "Open", icon: Activity, tone: "warning" },
      { key: "escalations", label: "Escalations", icon: Shield, tone: "danger" },
      { key: "resolved", label: "Resolved", icon: BadgeCheck, tone: "success" },
      { key: "response_time", label: "Avg Response", icon: Clock },
      { key: "agents", label: "Agents", icon: Users },
    ],
    table: {
      title: "Assist Requests",
      columns: [
        { key: "created_at", header: "When" },
        { key: "request", header: "Request" },
        { key: "agent", header: "Agent" },
        { key: "priority", header: "Priority" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "auto-dev": {
    moduleKey: "auto-dev",
    kicker: "Engineering",
    title: "Auto Dev",
    description: "Automated builds, deployments and failures from live records.",
    kpis: [
      { key: "builds", label: "Builds", icon: Code2 },
      { key: "deployments", label: "Deployments", icon: Server },
      { key: "success_rate", label: "Success Rate", icon: BadgeCheck, unit: "%", tone: "success" },
      { key: "failures", label: "Failures", icon: Bug, tone: "danger" },
      { key: "avg_duration", label: "Avg Duration", icon: Clock },
      { key: "queued", label: "Queued", icon: Activity, tone: "warning" },
    ],
    table: {
      title: "Build Runs",
      columns: [
        { key: "created_at", header: "When" },
        { key: "project", header: "Project" },
        { key: "branch", header: "Branch" },
        { key: "duration", header: "Duration" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "ai-ceo": {
    moduleKey: "ai-ceo",
    kicker: "Intelligence",
    title: "AI CEO",
    description: "AI-generated company insights and decisions from live records.",
    kpis: [
      { key: "insights", label: "Insights", icon: Sparkles },
      { key: "decisions", label: "Decisions", icon: BadgeCheck },
      { key: "risks", label: "Risks", icon: Shield, tone: "danger" },
      { key: "opportunities", label: "Opportunities", icon: TrendingUp, tone: "success" },
      { key: "modules_watched", label: "Modules Watched", icon: Boxes },
      { key: "accuracy", label: "Accuracy", icon: Target, unit: "%", tone: "success" },
    ],
    table: {
      title: "AI Observations",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "insight", header: "Insight" },
        { key: "impact", header: "Impact" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "api-manager": {
    moduleKey: "api-manager",
    kicker: "Platform",
    title: "API Manager",
    description: "API keys, quotas and gateway traffic from live records.",
    kpis: [
      { key: "endpoints", label: "Endpoints", icon: Code2 },
      { key: "keys", label: "Active Keys", icon: Shield },
      { key: "requests", label: "Requests", icon: Activity },
      { key: "errors", label: "Errors", icon: Bug, tone: "danger" },
      { key: "latency", label: "Avg Latency", icon: Clock },
      { key: "quota_used", label: "Quota Used", icon: TrendingUp, unit: "%", tone: "warning" },
    ],
    table: {
      title: "Endpoints",
      columns: [
        { key: "endpoint", header: "Endpoint" },
        { key: "method", header: "Method" },
        { key: "requests", header: "Requests" },
        { key: "errors", header: "Errors" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "ai-api": {
    moduleKey: "ai-api",
    kicker: "Platform",
    title: "AI & API Management",
    description: "AI providers, model usage and spend from live records.",
    kpis: [
      { key: "providers", label: "Providers", icon: Boxes },
      { key: "models", label: "Models", icon: Sparkles },
      { key: "requests", label: "Requests", icon: Activity },
      { key: "tokens", label: "Tokens", icon: TrendingUp },
      { key: "spend", label: "Spend", icon: CircleDollarSign, tone: "warning" },
      { key: "errors", label: "Errors", icon: Bug, tone: "danger" },
    ],
    table: {
      title: "Model Usage",
      columns: [
        { key: "provider", header: "Provider" },
        { key: "model", header: "Model" },
        { key: "requests", header: "Requests" },
        { key: "spend", header: "Spend" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "server-orchestration": {
    moduleKey: "server-orchestration",
    kicker: "Infrastructure",
    title: "Server Orchestration",
    description: "Clusters, nodes and workload placement from live records.",
    kpis: [
      { key: "clusters", label: "Clusters", icon: Boxes },
      { key: "nodes", label: "Nodes", icon: Server },
      { key: "cpu", label: "CPU", icon: Activity, unit: "%" },
      { key: "memory", label: "Memory", icon: TrendingUp, unit: "%" },
      { key: "incidents", label: "Incidents", icon: Bug, tone: "danger" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Nodes",
      columns: [
        { key: "node", header: "Node" },
        { key: "region", header: "Region" },
        { key: "cpu", header: "CPU" },
        { key: "memory", header: "Memory" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "unified-control": {
    moduleKey: "unified-control",
    kicker: "Command",
    title: "Unified Control",
    description: "Cross-module control, approvals and locks from live records.",
    kpis: [
      { key: "modules", label: "Modules", icon: Boxes },
      { key: "pending_approvals", label: "Pending Approvals", icon: Clock, tone: "warning" },
      { key: "locks", label: "Active Locks", icon: Shield, tone: "danger" },
      { key: "actions", label: "Actions Today", icon: Activity },
      { key: "operators", label: "Operators", icon: Users },
      { key: "health", label: "Health", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Control Actions",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "vala-builder": {
    moduleKey: "vala-builder",
    kicker: "Product",
    title: "Vala Builder",
    description: "Builder projects, templates and publishes from live records.",
    kpis: [
      { key: "projects", label: "Projects", icon: Boxes },
      { key: "templates", label: "Templates", icon: FileText },
      { key: "published", label: "Published", icon: BadgeCheck, tone: "success" },
      { key: "drafts", label: "Drafts", icon: Clock, tone: "warning" },
      { key: "builders", label: "Builders", icon: Users },
      { key: "build_errors", label: "Build Errors", icon: Bug, tone: "danger" },
    ],
    table: {
      title: "Builder Projects",
      columns: [
        { key: "project", header: "Project" },
        { key: "owner", header: "Owner" },
        { key: "template", header: "Template" },
        { key: "updated_at", header: "Updated" },
        { key: "status", header: "Status" },
      ],
    },
  },
  performance: {
    moduleKey: "performance",
    kicker: "Operations",
    title: "Performance Manager",
    description: "Team and system performance metrics from live records.",
    kpis: [
      { key: "score", label: "Score", icon: Target },
      { key: "reviews", label: "Reviews", icon: FileText },
      { key: "goals_met", label: "Goals Met", icon: BadgeCheck, tone: "success" },
      { key: "at_risk", label: "At Risk", icon: Activity, tone: "danger" },
      { key: "people", label: "People", icon: Users },
      { key: "trend", label: "Trend", icon: TrendingUp, unit: "%" },
    ],
    table: {
      title: "Performance Records",
      columns: [
        { key: "person", header: "Person" },
        { key: "role", header: "Role" },
        { key: "score", header: "Score" },
        { key: "period", header: "Period" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "internal-support": {
    moduleKey: "internal-support",
    kicker: "Support",
    title: "Internal Support AI",
    description: "Internal assistance requests handled by AI from live records.",
    kpis: [
      { key: "queries", label: "Queries", icon: LifeBuoy },
      { key: "auto_resolved", label: "Auto Resolved", icon: BadgeCheck, tone: "success" },
      { key: "escalated", label: "Escalated", icon: Shield, tone: "warning" },
      { key: "avg_response", label: "Avg Response", icon: Clock },
      { key: "satisfaction", label: "Satisfaction", icon: TrendingUp, unit: "%", tone: "success" },
      { key: "agents", label: "Agents", icon: Users },
    ],
    table: {
      title: "Support Queries",
      columns: [
        { key: "created_at", header: "When" },
        { key: "requester", header: "Requester" },
        { key: "topic", header: "Topic" },
        { key: "handled_by", header: "Handled By" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "dev-command": {
    moduleKey: "dev-command",
    kicker: "Engineering",
    title: "Dev Command Center",
    description: "Engineering workload, releases and defects from live records.",
    kpis: [
      { key: "repos", label: "Repos", icon: Code2 },
      { key: "open_prs", label: "Open PRs", icon: Activity, tone: "warning" },
      { key: "releases", label: "Releases", icon: Server },
      { key: "bugs", label: "Bugs", icon: Bug, tone: "danger" },
      { key: "developers", label: "Developers", icon: Users },
      { key: "velocity", label: "Velocity", icon: TrendingUp },
    ],
    table: {
      title: "Engineering Records",
      columns: [
        { key: "created_at", header: "When" },
        { key: "repo", header: "Repo" },
        { key: "item", header: "Item" },
        { key: "owner", header: "Owner" },
        { key: "status", header: "Status" },
      ],
    },
  },
  influencer_dashboard: {
    moduleKey: "influencer",
    kicker: "Growth",
    title: "Influencer Dashboard",
    description: "Campaign participation, reach and payouts from live records.",
    kpis: [
      { key: "campaigns", label: "Campaigns", icon: Megaphone },
      { key: "reach", label: "Reach", icon: TrendingUp },
      { key: "conversions", label: "Conversions", icon: Target, tone: "success" },
      { key: "earnings", label: "Earnings", icon: Wallet, tone: "success" },
      { key: "pending_payouts", label: "Pending Payouts", icon: Clock, tone: "warning" },
      { key: "rating", label: "Rating", icon: BadgeCheck },
    ],
    table: {
      title: "Campaign Records",
      columns: [
        { key: "campaign", header: "Campaign" },
        { key: "channel", header: "Channel" },
        { key: "reach", header: "Reach" },
        { key: "earnings", header: "Earnings" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "promise-tracker": {
    moduleKey: "promise",
    kicker: "Governance",
    title: "Promise Tracker",
    description: "Tracked commitments and delivery progress from live records.",
    kpis: [
      { key: "promises", label: "Promises", icon: ListChecks },
      { key: "delivered", label: "Delivered", icon: BadgeCheck, tone: "success" },
      { key: "in_progress", label: "In Progress", icon: Activity },
      { key: "overdue", label: "Overdue", icon: Clock, tone: "danger" },
      { key: "owners", label: "Owners", icon: Users },
      { key: "on_time_rate", label: "On-time Rate", icon: TrendingUp, unit: "%", tone: "success" },
    ],
    table: {
      title: "Tracked Promises",
      columns: [
        { key: "promise", header: "Promise" },
        { key: "owner", header: "Owner" },
        { key: "due_date", header: "Due" },
        { key: "progress", header: "Progress" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "search-console": {
    moduleKey: "seo",
    kicker: "Growth",
    title: "SEO Manager",
    description: "Rankings, traffic and indexation from live records.",
    kpis: [
      { key: "keywords", label: "Keywords", icon: Search },
      { key: "impressions", label: "Impressions", icon: Activity },
      { key: "clicks", label: "Clicks", icon: Target },
      { key: "avg_position", label: "Avg Position", icon: TrendingUp },
      { key: "indexed", label: "Indexed Pages", icon: FileText },
      { key: "issues", label: "Issues", icon: Bug, tone: "danger" },
    ],
    table: {
      title: "Keyword Records",
      columns: [
        { key: "keyword", header: "Keyword" },
        { key: "page", header: "Page" },
        { key: "position", header: "Position" },
        { key: "clicks", header: "Clicks" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "master-admin-supreme": {
    moduleKey: "master-admin",
    kicker: "Supreme",
    title: "Master Admin Supreme",
    description: "Supreme oversight of every module, actor and system signal from live records.",
    kpis: [
      { key: "modules", label: "Live Modules", icon: Boxes },
      { key: "users", label: "Active Users", icon: Users },
      { key: "actions", label: "Actions Today", icon: Activity },
      { key: "flags", label: "AI Flags", icon: Shield, tone: "warning" },
      { key: "incidents", label: "Open Incidents", icon: Bug, tone: "danger" },
      { key: "uptime", label: "Uptime", icon: BadgeCheck, unit: "%", tone: "success" },
    ],
    table: {
      title: "Supreme Activity Log",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "risk", header: "Risk" },
      ],
    },
  },
  "command-center": {
    moduleKey: "command-center",
    kicker: "Command",
    title: "Super Admin Command Center",
    description: "Cross-module command and control metrics from live records.",
    kpis: [
      { key: "leads", label: "Leads", icon: Target },
      { key: "orders", label: "Orders", icon: ShoppingCart },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "tickets", label: "Open Tickets", icon: LifeBuoy, tone: "warning" },
      { key: "users", label: "Active Users", icon: Users },
      { key: "alerts", label: "Alerts", icon: Activity, tone: "danger" },
    ],
    table: {
      title: "Command Feed",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "event", header: "Event" },
        { key: "owner", header: "Owner" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "secure-control": {
    moduleKey: "secure-control",
    kicker: "Governance",
    title: "Secure Control Workspace",
    description: "Forwarded actions, behaviour scores and risk flags from live records.",
    kpis: [
      { key: "pending_actions", label: "Pending Actions", icon: ListChecks, tone: "warning" },
      { key: "approved", label: "Approved", icon: BadgeCheck, tone: "success" },
      { key: "risk_flags", label: "Risk Flags", icon: Shield, tone: "danger" },
      { key: "behaviour_score", label: "Avg Behaviour Score", icon: UserCheck },
      { key: "ledger_entries", label: "Ledger Entries", icon: FileText },
      { key: "actors", label: "Monitored Actors", icon: Users },
    ],
    table: {
      title: "Forwarded Actions",
      columns: [
        { key: "created_at", header: "When" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "risk", header: "Risk" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "master-admin-workspace": {
    moduleKey: "master-admin",
    kicker: "Governance",
    title: "Master Admin Workspace",
    description: "Flagged items, approvals and immutable ledger from live records.",
    kpis: [
      { key: "flagged", label: "Flagged Items", icon: Shield, tone: "warning" },
      { key: "approvals", label: "Pending Approvals", icon: ListChecks },
      { key: "resolved", label: "Resolved", icon: BadgeCheck, tone: "success" },
      { key: "ledger_entries", label: "Ledger Entries", icon: FileText },
      { key: "modules", label: "Modules", icon: Boxes },
      { key: "critical", label: "Critical", icon: Bug, tone: "danger" },
    ],
    table: {
      title: "Flagged Items",
      columns: [
        { key: "created_at", header: "When" },
        { key: "module", header: "Module" },
        { key: "item", header: "Item" },
        { key: "risk", header: "Risk" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "secure-control-system": {
    moduleKey: "secure-control",
    kicker: "Governance",
    title: "Secure Control System",
    description: "System-wide secure control, approvals and audit trail from live records.",
    kpis: [
      { key: "pending_actions", label: "Pending Actions", icon: ListChecks, tone: "warning" },
      { key: "approved", label: "Approved", icon: BadgeCheck, tone: "success" },
      { key: "rejected", label: "Rejected", icon: Bug, tone: "danger" },
      { key: "audit_events", label: "Audit Events", icon: FileText },
      { key: "actors", label: "Actors", icon: Users },
      { key: "sessions", label: "Active Sessions", icon: Clock },
    ],
    table: {
      title: "Control Actions",
      columns: [
        { key: "created_at", header: "When" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "module", header: "Module" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "master-admin-control": {
    moduleKey: "master-admin",
    kicker: "Governance",
    title: "Master Admin Control",
    description: "Forwarded actions and AI reports awaiting master decision, from live records.",
    kpis: [
      { key: "pending_actions", label: "Pending Actions", icon: ListChecks, tone: "warning" },
      { key: "ai_flags", label: "AI Flags", icon: Sparkles, tone: "danger" },
      { key: "approved", label: "Approved", icon: BadgeCheck, tone: "success" },
      { key: "reports", label: "AI Reports", icon: FileText },
      { key: "modules", label: "Modules", icon: Boxes },
      { key: "actors", label: "Actors", icon: Users },
    ],
    table: {
      title: "Forwarded Actions",
      columns: [
        { key: "created_at", header: "When" },
        { key: "actor", header: "Actor" },
        { key: "action", header: "Action" },
        { key: "risk_flag", header: "Risk" },
        { key: "status", header: "Status" },
      ],
    },
  },
  "server-portal": {
    moduleKey: "server-manager",
    kicker: "Infrastructure",
    title: "Server Management Portal",
    description: "Server fleet health, resources and access events from live records.",
    kpis: [
      { key: "servers", label: "Servers", icon: Server },
      { key: "online", label: "Online", icon: BadgeCheck, tone: "success" },
      { key: "cpu_usage", label: "Avg CPU", icon: Activity, unit: "%" },
      { key: "ram_usage", label: "Avg RAM", icon: Activity, unit: "%" },
      { key: "disk_usage", label: "Avg Disk", icon: Boxes, unit: "%" },
      { key: "incidents", label: "Incidents", icon: Bug, tone: "danger" },
    ],
    table: {
      title: "Server Records",
      columns: [
        { key: "name", header: "Server" },
        { key: "region", header: "Region" },
        { key: "cpu_usage", header: "CPU %" },
        { key: "ram_usage", header: "RAM %" },
        { key: "status", header: "Status" },
      ],
    },
  },
  enterprise: {
    moduleKey: "enterprise",
    kicker: "Enterprise",
    title: "Enterprise Dashboard",
    description: "Company-wide enterprise metrics and activity from live records.",
    kpis: [
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "orders", label: "Orders", icon: ShoppingCart },
      { key: "customers", label: "Customers", icon: Users },
      { key: "modules_active", label: "Active Modules", icon: Boxes },
      { key: "alerts", label: "Alerts", icon: Shield, tone: "warning" },
      { key: "uptime", label: "Uptime", icon: Activity, unit: "%" },
    ],
    table: {
      title: "Enterprise Activity",
      columns: [
        { key: "entity", header: "Entity" },
        { key: "module", header: "Module" },
        { key: "amount", header: "Amount" },
        { key: "status", header: "Status" },
        { key: "updated_at", header: "Updated" },
      ],
    },
  },
  "reseller-portal": {
    moduleKey: "reseller",
    kicker: "Partners",
    title: "Reseller Portal",
    description: "Reseller sales, commissions and client records from live data.",
    kpis: [
      { key: "clients", label: "Clients", icon: Users },
      { key: "sales", label: "Sales", icon: ShoppingCart },
      { key: "revenue", label: "Revenue", icon: CircleDollarSign, tone: "success" },
      { key: "commission", label: "Commission", icon: Wallet },
      { key: "pending", label: "Pending", icon: Clock, tone: "warning" },
      { key: "conversion", label: "Conversion", icon: TrendingUp, unit: "%" },
    ],
    table: {
      title: "Reseller Records",
      columns: [
        { key: "client", header: "Client" },
        { key: "plan", header: "Plan" },
        { key: "amount", header: "Amount" },
        { key: "commission", header: "Commission" },
        { key: "status", header: "Status" },
      ],
    },
  },
};

